### PR TITLE
Feature/   add initial files

### PR DESCRIPTION
**Pull request by MWMJohnson**
## High level what you did: 
I added the the following files
1.  Added file_io.rb under our lib as a runner file and placed in the exact code from the example under "File I/O" in iteration 2.
2. Added stat_tracker.rb under our lib and kept empty, and then added 3 spec files for game, team, and season statistics. Based on methods required and their descriptions, I built out initial describe and it blocks for each method that will need to be tested. Commented out the test for now, so `rspec spec` will run.
### Details: 
Also Adjusted the spec_helper.rb by moving the `require 'rspec' ` below `SimpleCov.start`.
## Issues: 
We will need to add the specs, I truly just built out an initial format. Please let me know if you feel like we build just one big spec file instead of the three I have created and if we are missing any other files at this time.
## Questions: 
Regarding the files I created I was hesitant to add the spec helper, because from what I understand about the spec harness is that we might have to use `require_relative` rather than `require`.
## Overall:
- [NA ] Tests are written for all methods added
- [ X ] Rspec running clean
- [ See below ] Bugs, need help, etc. 
If we uncomment out the current tests I have written they will technically fail because of an uninitialized constant error, because we have not added our StatTracker class yet.

### CODE REVIEW

**Comment by aplasket** [comment]
hey @MWMJohnson thanks for adding all these. 
I noticed season_statistics.rb is in the spec directory - should that be named season_statistics_spec.rb or are you wanting for that to be the class file? if class file can you move up to lib and create a spec file to match in the spec directory? 

also we'll probably need the matching class files in the lib directory for game_statistics.rb, and league_statistics.rb. would you mind adding that to this PR so we have all the classes in one? 

Or I'm happy to do it too if that's easier - I can create a branch and submit a PR. lmk! thank you!

**Comment by MWMJohnson** [comment]
Hey @aplasket 
I went ahead and made the edits and have pushed them back up, but just curious I though we were supposed to have all of our methods in the StatTracker class so we would not need a lib file for each statistic?

**Comment by aplasket** [comment]
@MWMJohnson  - youre totally right. in the spirit of YAGNI, we may/may not need some of these classes or specs. So totally ok for us to leave it out for now if you'd prefer!

**Comment by MWMJohnson** [comment]
Hey @aplasket ,I am good to leave them in for now, and we can always delete later if not needed.

**Comment by aplasket** [comment]
cool, sounds great. thanks again for working on this!!

**Pull request merged**
